class_name HutInterior
extends Node3D
## Root of the hut interior scene (docs §11, group hut_interior), generated by
## hut_interior_builder.gd from data/world/hut_interior_layout.json and instanced by the world
## builder far from the graveyard (origin (0, 0, −200)). Holds the room, furniture, entities
## (Bed, Stove, Chest, Desk, InteriorDoor), colliders, lights (InteriorLighting) and its own
## "camera": the CameraRig profile (distance, room bounds, own Environment) and a soft Sun.
## On EventBus.interior_changed it swaps the view: rig profile, interior sun ↔ outdoor sun.

const GROUP := &"hut_interior"

@export var config: InteriorConfig
## Camera environment while inside (the graveyard's fog and moonlight stay outside).
@export var environment: Environment
@export var camera_attributes: CameraAttributes
## Focus bounds of the interior camera, room-local XZ.
@export var bounds_min: Vector2 = Vector2(-0.5, -0.3)
@export var bounds_max: Vector2 = Vector2(0.5, 0.3)
## Set by the world builder: the CameraRig and the outdoor DirectionalLight3D.
@export var camera_rig_path: NodePath
@export var outdoor_sun_path: NodePath

## True while the view shows the interior.
var active: bool = false

@onready var sun: DirectionalLight3D = get_node_or_null(^"Sun") as DirectionalLight3D
@onready var spawn: Marker3D = get_node_or_null(^"Spawn") as Marker3D


func _init() -> void:
	add_to_group(GROUP)


func _ready() -> void:
	config = InteriorConfig.resolve(config)
	if sun != null:
		sun.visible = false
	EventBus.interior_changed.connect(apply_view)


## Where the gravekeeper appears when entering: spawn_inside, facing into the room (−Z).
func spawn_transform() -> Transform3D:
	if spawn == null:
		return global_transform
	return spawn.global_transform if spawn.is_inside_tree() else transform * spawn.transform


## The CameraRig profile of the room: config distance / zoom, bounds around the room, own env.
func camera_profile() -> CameraProfile:
	var p := CameraProfile.new()
	p.distance = config.camera_distance
	p.zoom_min = config.camera_zoom_min
	p.zoom_max = config.camera_zoom_max
	var origin := global_position if is_inside_tree() else position
	p.bounds_enabled = true
	p.bounds_min = Vector2(origin.x, origin.z) + bounds_min
	p.bounds_max = Vector2(origin.x, origin.z) + bounds_max
	p.environment = environment
	p.attributes = camera_attributes
	return p


## Shows the interior (true) or the graveyard (false): interior sun, outdoor sun, rig profile.
func apply_view(inside: bool) -> void:
	if not is_inside_tree():
		return
	active = inside
	if sun != null:
		sun.visible = inside
	var outdoor := get_node_or_null(outdoor_sun_path) as Light3D if not outdoor_sun_path.is_empty() else null
	if outdoor != null:
		outdoor.visible = not inside
	var rig := get_node_or_null(camera_rig_path) as CameraRig if not camera_rig_path.is_empty() else null
	if rig == null or not rig.is_node_ready():
		return
	if inside:
		rig.set_profile(camera_profile())
	else:
		rig.clear_profile()
	rig.snap()
