class_name HutInterior
extends InteriorRoom
## Root of the hut interior scene (docs §11, group hut_interior), generated by
## hut_interior_builder.gd from data/world/hut_interior_layout.json and instanced by the world
## builder far from the graveyard (origin (0, 0, −200)). Holds the room, furniture, entities
## (Bed, Stove, Chest, Desk, InteriorDoor), colliders, lights (InteriorLighting) and its own
## "camera": the CameraRig profile (distance, room bounds, own Environment) and a soft Sun.
## Phase 6 (§3.4): the room core lives in InteriorRoom (room_id &"hut", never hidden, no levels);
## the view follows EventBus.interior_room_changed. apply_view(inside) stays for compatibility.
##
## Note: InteriorRoom.GROUP (&"interior_room") cannot be redeclared in a subclass, so the hut's own
## group is HUT_GROUP (= &"hut_interior", unchanged); HutInterior.GROUP is the inherited room group.

const HUT_GROUP := &"hut_interior"


func _init() -> void:
	add_to_group(HUT_GROUP)
	room_id = InteriorRoom.HUT


## Shows the interior (true) or the graveyard (false) = apply_room(&"hut" | &"").
func apply_view(inside: bool) -> void:
	apply_room(room_id if inside else &"")
