class_name WorldRoot
extends Node3D
## Root of the graveyard world scene (generated by graveyard_builder.gd, §4).
## Collects the systems, looks up layout ids and waypoints, and announces
## EventBus.world_ready(self) deferred after _ready (all children are ready by then).
## _ready builds no game content – SaveManager's new_game / load does that.

const SYSTEMS := ^"Systems"
const ENTITIES := ^"Entities"
const OLD_GRAVES := ^"Decor/OldGraves"
const WAYPOINTS := ^"Waypoints"
const PLAYER := ^"Player"
const GROUND_SHAPE := ^"GroundCollision/Shape"
const GROUND := ^"Ground"
const DECOR := ^"Decor"
## Render layer of meshes with foliage surfaces (tree crowns, bushes): the only painted material
## that sways (TIME in vertex()), which makes Godot redraw every shadow map in its range each
## frame. The warm lights (lanterns) leave this layer out of their shadow casters, so their
## cube shadows stay cached; the sun still gets the trees' shadows (PERF-01).
const FOLIAGE_LAYER := 1 << 1
const FOLIAGE_SHADER := "res://assets/shaders/painted_foliage.gdshader"
const WARM_LIGHTS := &"warm_lights"

var corpse_manager: CorpseManager
var graveyard: Graveyard
var is_world_ready: bool = false

var _heightmap: HeightMapShape3D
var _heightmap_xform: Transform3D


func _ready() -> void:
	corpse_manager = get_node_or_null(^"Systems/CorpseManager") as CorpseManager
	graveyard = get_node_or_null(^"Systems/Graveyard") as Graveyard
	if corpse_manager == null or graveyard == null:
		push_warning("[WorldRoot] Systems/CorpseManager or Systems/Graveyard missing")
	_ground_receives_shadows_only()
	_foliage_out_of_warm_shadows()
	_announce.call_deferred()


## World position of Waypoints/<id> (Vector3.ZERO + warning when unknown).
func get_waypoint(id: StringName) -> Vector3:
	var marker := get_node_or_null(NodePath("%s/%s" % [WAYPOINTS, id])) as Node3D
	if marker == null:
		push_warning("[WorldRoot] unknown waypoint '%s'" % id)
		return Vector3.ZERO
	return marker.global_position if marker.is_inside_tree() else _relative_xform(marker).origin


## Yaw (rad) an NPC standing at Waypoints/<id> should face (layout waypoint_facing); NAN = none.
func get_waypoint_facing(id: StringName) -> float:
	var marker := get_node_or_null(NodePath("%s/%s" % [WAYPOINTS, id])) as Node3D
	if marker == null or not marker.has_meta(&"facing"):
		return NAN
	return marker.rotation.y


func get_player() -> Player:
	return get_node_or_null(PLAYER) as Player


## Entities/<id> or Decor/OldGraves/<id>; null when the layout has no such id.
func get_node_by_layout_id(id: String) -> Node:
	for parent: NodePath in [ENTITIES, OLD_GRAVES]:
		var node := get_node_or_null(NodePath("%s/%s" % [parent, id]))
		if node != null:
			return node
	return null


## Height of the ground at world (x, z) from the ground collision heightmap (0 without one).
## Usable before _ready (children, e.g. the NPC, place themselves during their own _ready).
func ground_height(pos: Vector2) -> float:
	if _heightmap == null:
		var shape_node := get_node_or_null(GROUND_SHAPE) as CollisionShape3D
		if shape_node == null or not shape_node.shape is HeightMapShape3D:
			return 0.0
		_heightmap = shape_node.shape as HeightMapShape3D
		_heightmap_xform = _relative_xform(shape_node)
	var local := _heightmap_xform.affine_inverse() * Vector3(pos.x, 0.0, pos.y)
	var w := _heightmap.map_width
	var d := _heightmap.map_depth
	var gx := clampf(local.x + (w - 1) * 0.5, 0.0, w - 1.0)
	var gz := clampf(local.z + (d - 1) * 0.5, 0.0, d - 1.0)
	var x0 := mini(floori(gx), w - 2)
	var z0 := mini(floori(gz), d - 2)
	var fx := gx - x0
	var fz := gz - z0
	var data := _heightmap.map_data
	var h00 := data[z0 * w + x0]
	var h10 := data[z0 * w + x0 + 1]
	var h01 := data[(z0 + 1) * w + x0]
	var h11 := data[(z0 + 1) * w + x0 + 1]
	var h := lerpf(lerpf(h00, h10, fx), lerpf(h01, h11, fx), fz)
	return (_heightmap_xform * Vector3(local.x, h, local.z)).y


## The ground is one large mesh that only receives shadows; casting would draw it into every
## shadow pass (sun splits + omni cube faces) – most of the triangle budget. Set here because
## an override inside the imported .glb instance would embed the whole mesh in the scene.
func _ground_receives_shadows_only() -> void:
	var ground := get_node_or_null(GROUND)
	if ground == null:
		return
	for mesh: Node in ground.find_children("*", "GeometryInstance3D", true, false):
		(mesh as GeometryInstance3D).cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF


## Foliage meshes (Decor, and the brambles / thorn hedge among the Phase-3 obstacles in
## Entities) go to FOLIAGE_LAYER only, and every warm light of the world stops casting shadows
## from that layer (see FOLIAGE_LAYER). Runtime for the same reason as above.
func _foliage_out_of_warm_shadows() -> void:
	for path: NodePath in [DECOR, ENTITIES]:
		var parent := get_node_or_null(path)
		if parent == null:
			continue
		for node: Node in parent.find_children("*", "MeshInstance3D", true, false):
			var mesh := node as MeshInstance3D
			if _has_foliage(mesh):
				mesh.layers = FOLIAGE_LAYER
	for node: Node in get_tree().get_nodes_in_group(WARM_LIGHTS):
		if node is Light3D and is_ancestor_of(node):
			var light := node as Light3D
			light.shadow_caster_mask = light.shadow_caster_mask & ~FOLIAGE_LAYER


static func _has_foliage(mesh: MeshInstance3D) -> bool:
	if mesh.mesh == null:
		return false
	for i: int in mesh.mesh.get_surface_count():
		var mat := mesh.get_active_material(i) as ShaderMaterial
		if mat != null and mat.shader != null and mat.shader.resource_path == FOLIAGE_SHADER:
			return true
	return false


func _announce() -> void:
	is_world_ready = true
	EventBus.world_ready.emit(self)


## Transform of `node` relative to this root (works before the node is in the tree).
func _relative_xform(node: Node3D) -> Transform3D:
	var xform := Transform3D.IDENTITY
	var n: Node = node
	while n != null and n != self:
		if n is Node3D:
			xform = (n as Node3D).transform * xform
		n = n.get_parent()
	return xform
